### ISSUE TITLE
Release v1.6.0

### ISSUE THREAD

**Issue by sdenef** [Open-Wide/owsi-nuxeo-commons#1]
Hello,

Did you schedule to release v1.6.0 ?

Thanks

**Comment by mkalam-alami** [comment]
Hi Neoh,

We didn't take the time to release it, but I can take a moment to do it if you need that version.

In the meantime feel free to use the 1.7.10 version, which should be retro-compatible.

**Comment by sdenef** [comment]
For the moment, I use a locally packaged v1.6.0-snapshot and I added jars to my local Maven repo.

So yes, do it if it's easy for you to release this version please.

**Comment by mkalam-alami** [comment]
I just released the 1.6.0 version, it should appear in Maven Central in a matter of hours.

Regards
